# Generated by Django 3.2.16 on 2023-06-24 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='city',
            new_name='asal_kota',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='country',
            new_name='sekolah',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='profile',
            name='no_telpon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='token',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
