# Generated by Django 3.2.16 on 2023-06-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pertanyaan',
            name='nilai',
        ),
        migrations.AddField(
            model_name='pertanyaan',
            name='jawaban_benar',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=100, null=True),
        ),
    ]
