# Generated by Django 3.2.16 on 2023-06-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20230624_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='pertanyaan',
            name='bobot',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
