# Generated by Django 3.2.16 on 2023-06-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_pertanyaan_bobot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pertanyaan',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
