# Generated by Django 3.2.16 on 2023-06-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_pertanyaan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategori',
            name='penjelasan',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
