# Generated by Django 3.2.16 on 2023-06-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_kategori_penjelasan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pertanyaan',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
