# Generated by Django 3.2.16 on 2023-06-24 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_alter_pertanyaan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hasil',
            name='kategori',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.kategori'),
        ),
    ]
