# Generated by Django 3.2.16 on 2023-06-25 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_hasil_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategori',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='kategori/icon'),
        ),
    ]
