# Generated by Django 3.2.16 on 2023-06-24 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_bot_ai_pengguna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot_ai',
            name='kunci',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.kunci'),
        ),
    ]
